In [13]:
import nose.tools as nt
import os
import sys
import numpy as np
import optparse
import shutil
import re
from copy import deepcopy
import aipy
from omnical.calib import RedundantInfo
from pyuvdata import UVCal, UVData
import hera_cal.omni as omni
reload(omni)
from hera_cal.data import DATA_PATH
from hera_cal.calibrations import CAL_PATH

SyntaxError: invalid syntax (omni.py, line 372)

In [ ]:


# multi pol tests
global visXX, visXY, visYX, visYY
global fcalXX, fcalYY
calfile = 'hsa7458_v001'
visXX = 'zen.2457698.40355.xx.HH.uvcA'
visXY = 'zen.2457698.40355.xy.HH.uvcA'
visYX = 'zen.2457698.40355.yx.HH.uvcA'
visYY = 'zen.2457698.40355.yy.HH.uvcA'
fcalXX = 'zen.2457698.40355.xx.HH.uvcA.first.calfits'
fcalYY = 'zen.2457698.40355.yy.HH.uvcA.first.calfits'
if CAL_PATH not in sys.path:
    sys.path.append(CAL_PATH)

objective_file = os.path.join(DATA_PATH, 'zen.2457698.40355.HH.uvcA.omni.calfits')
if os.path.exists(objective_file):
    os.remove(objective_file)
o = omni.get_optionParser('omni_run')
visxx = os.path.join(DATA_PATH, visXX)
visxy = os.path.join(DATA_PATH, visXY)
visyx = os.path.join(DATA_PATH, visYX)
visyy = os.path.join(DATA_PATH, visYY)
fcalxx = os.path.join(DATA_PATH, 'test_input', fcalXX)
fcalyy = os.path.join(DATA_PATH, 'test_input', fcalYY)

cmd = "-C %s -p xx,xy,yx,yy --firstcal=%s,%s --ex_ants=81 --omnipath=%s %s %s %s %s" % (
    calfile, fcalxx, fcalyy, DATA_PATH, visxx, visxy, visyx, visyy)

opts, files = o.parse_args(cmd.split())
history = 'history'
omni.omni_run(files, opts, history)
#nt.assert_true(os.path.exists(objective_file))
# clean up
# os.remove(objective_file)
# visfile = re.sub('omni\.calfits', 'vis.uvfits', objective_file)
# xtalkfile = re.sub('omni\.calfits', 'xtalk.uvfits', objective_file)
# os.remove(visfile)
# os.remove(xtalkfile)

Getting reds from calfile
   Excluding antennas: [81]
/Users/jsdillon/anaconda2/lib/python2.7/site-packages/hera_cal-0.0.0-py2.7.egg/hera_cal/data/test_input/zen.2457698.40355.xx.HH.uvcA.first.calfits
/Users/jsdillon/anaconda2/lib/python2.7/site-packages/hera_cal-0.0.0-py2.7.egg/hera_cal/data/test_input/zen.2457698.40355.yy.HH.uvcA.first.calfits
   Running Omnical
Python 2.7.13 |Anaconda custom (x86_64)| (default, Dec 20 2016, 23:05:08) 
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: positions.shape
Out[1]: (36, 2)

In [2]: np.hstack(positions, np.ones(36))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/Users/


In [8]: gainPols=='x'
Out[8]: 
array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False], dtype=bool)

In [9]: hstack((gainPols=='x',gainPols=='y'))
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/Users/jsdillon/anaconda2/lib/python2.7/site-packages/hera_cal-0.0.0-py2.7.egg/hera_cal/omni.pyc in <module>()
----> 1 hstack((gainPols=='x',gainPols=='y'))

NameError: name 'hstack' is not defined

In [10]: np.hstack((gainPols=='x',gainPols=='y'))
Out[10]: 
array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       

In [12]:
np.append(np.arange(3),[.2,.3])

array([ 0. ,  1. ,  2. ,  0.2,  0.3])

In [2]:
# single pol tests
global xx_vis, calfile, xx_fcal
xx_vis = 'zen.2457698.40355.xx.HH.uvcAA'
calfile = 'hsa7458_v001'
xx_fcal = 'zen.2457698.40355.xx.HH.uvcAA.first.calfits'

objective_file = os.path.join(
    DATA_PATH, 'test_output', 'zen.2457698.40355.xx.HH.uvcAA.omni.calfits')
if os.path.exists(objective_file):
    os.remove(objective_file)
o = omni.get_optionParser('omni_run')
xx_fcal4real = os.path.join(DATA_PATH, 'test_input', xx_fcal)
xx_vis4real = os.path.join(DATA_PATH, xx_vis)
omnipath = os.path.join(DATA_PATH, 'test_output')

cmd = "-C %s -p xx --firstcal=%s --ex_ants=81 --omnipath=%s %s" % (
    calfile, xx_fcal4real, omnipath, xx_vis4real)
opts, files = o.parse_args(cmd.split())
history = 'history'
omni.omni_run(files, opts, history)
nt.assert_true(os.path.exists(objective_file))
os.remove(objective_file)

Getting reds from calfile
   Excluding antennas: [81]
/Users/jsdillon/anaconda2/lib/python2.7/site-packages/hera_cal-0.0.0-py2.7.egg/hera_cal/data/test_input/zen.2457698.40355.xx.HH.uvcAA.first.calfits
   Running Omnical
['x']
['xx']
   Saving /Users/jsdillon/anaconda2/lib/python2.7/site-packages/hera_cal-0.0.0-py2.7.egg/hera_cal/data/test_output/zen.2457698.40355.xx.HH.uvcAA.omni.calfits
The data are in drift mode and do not have a defined phase center. Phasing to zenith of the first timestamp.
The data are in drift mode and do not have a defined phase center. Phasing to zenith of the first timestamp.


In [19]:
import aipy as a
freqs = np.arange(.1,.2,.1/1024)
aa = a.cal.get_aa('hsa7458_v001', freqs)
aa.

array([[ -1.        ,  -1.        ,  -1.        ],
       [ -1.        ,  -1.        ,  -1.        ],
       [ -1.        ,  -1.        ,  -1.        ],
       [ -1.        ,  -1.        ,  -1.        ],
       [ -1.        ,  -1.        ,  -1.        ],
       [ -1.        ,  -1.        ,  -1.        ],
       [ -1.        ,  -1.        ,  -1.        ],
       [ -1.        ,  -1.        ,  -1.        ],
       [ -1.        ,  -1.        ,  -1.        ],
       [-14.6       ,   0.        ,   0.        ],
       [ 21.9       ,  12.6439709 ,   0.        ],
       [ -1.        ,  -1.        ,  -1.        ],
       [ -1.        ,  -1.        ,  -1.        ],
       [ -1.        ,  -1.        ,  -1.        ],
       [ -1.        ,  -1.        ,  -1.        ],
       [ -1.        ,  -1.        ,  -1.        ],
       [ -1.        ,  -1.        ,  -1.        ],
       [ -1.        ,  -1.        ,  -1.        ],
       [ -1.        ,  -1.        ,  -1.        ],
       [ -1.        ,  -1.     

In [20]:
aa.antpos_ideal.shape

(128, 3)

In [22]:
info = omni.aa_to_info(aa, pols=['x','y'], fcal=False, minV=False)

In [27]:
info.get_antpos()

(241, 3)

In [34]:
test = []

for n in range(128):
    try:
        test.append(info.get_antpos()[n,:] == info.get_antpos()[n+128,:])
    except:
        pass

In [40]:
np.all(np.array(test)[:,0:2])

True

In [46]:
info.get_antpos()[81,0:2]

array([  7.30000019,  12.64397049])