# Devising a new unit test

In [10]:
import omnical.info as Oi, omnical.calib as Oc, omnical._omnical as _O
from copy import deepcopy
import numpy as np

antpos = np.array([[ 14.60000038, -25.28794098,   1.], [ 21.89999962, -12.64397049,   1.], [ 14.60000038,  25.28794098,   1.], [-21.89999962, -12.64397049,   1.], [-14.60000038,   0.        ,   1.], [ 21.89999962,  12.64397049,   1.], [ 29.20000076,   0.        ,   1.], [-14.60000038, -25.28794098,   1.], [  0.        ,  25.28794098,   1.], [  0.        , -25.28794098,   1.], [  0.        ,   0.        ,   1.], [ -7.30000019, -12.64397049,   1.], [ -7.30000019,  12.64397049,   1.], [-21.89999962,  12.64397049,   1.], [-29.20000076,   0.        ,   1.], [ 14.60000038,   0.        ,   1.], [-14.60000038,  25.28794098,   1.], [  7.30000019, -12.64397049,   1.]])
reds = [[(0, 8), (9, 16)], [(13, 15), (14, 17), (3, 0), (4, 1), (16, 5), (12, 6)], [(3, 17), (4, 15), (7, 0), (11, 1), (16, 2), (12, 5), (10, 6), (14, 10)], [(3, 6), (14, 5)], [(0, 9), (1, 17), (2, 8), (4, 14), (6, 15), (8, 16), (12, 13), (11, 3), (10, 4), (9, 7), (15, 10), (17, 11)], [(3, 8), (11, 2), (9, 5)], [(3, 9), (4, 17), (12, 15), (11, 0), (10, 1), (8, 5), (13, 10), (14, 11)], [(0, 13), (1, 16)], [(0, 4), (1, 12), (6, 8), (9, 14), (15, 16), (17, 13)], [(0, 5), (3, 16), (7, 12), (17, 2), (11, 8)], [(0, 10), (7, 14), (10, 16), (11, 13), (6, 2), (9, 4), (15, 8), (17, 12)], [(1, 9), (2, 12), (5, 10), (6, 17), (8, 13), (12, 14), (10, 3), (17, 7), (15, 11)], [(2, 3), (5, 7)], [(16, 17), (12, 0), (8, 1), (13, 9)], [(0, 17), (1, 15), (3, 14), (4, 13), (9, 11), (10, 12), (12, 16), (5, 2), (7, 3), (11, 4), (6, 5), (17, 10)], [(3, 15), (4, 5), (7, 1), (13, 2), (11, 6)], [(5, 15), (8, 12), (10, 11), (13, 14), (15, 17), (1, 0), (6, 1), (4, 3), (12, 4), (11, 7), (17, 9), (16, 13)], [(0, 15), (1, 5), (3, 13), (4, 16), (9, 10), (11, 12), (15, 2), (7, 4), (10, 8)], [(0, 6), (3, 12), (4, 8), (7, 10), (9, 15), (14, 16), (10, 2), (17, 5)], [(8, 17), (2, 1), (13, 7), (12, 9), (16, 11)], [(0, 2), (7, 16), (9, 8)], [(4, 6), (14, 15), (3, 1), (13, 5)], [(0, 14), (1, 13), (6, 16)], [(2, 14), (6, 7), (5, 3)], [(2, 9), (8, 7)], [(2, 4), (5, 11), (6, 9), (8, 14), (15, 7)], [(1, 14), (6, 13)], [(0, 8), (9, 16)], [(13, 15), (14, 17), (3, 0), (4, 1), (16, 5), (12, 6)], [(3, 17), (4, 15), (7, 0), (11, 1), (16, 2), (12, 5), (10, 6), (14, 10)], [(3, 6), (14, 5)], [(0, 9), (1, 17), (2, 8), (4, 14), (6, 15), (8, 16), (12, 13), (11, 3), (10, 4), (9, 7), (15, 10), (17, 11)], [(3, 8), (11, 2), (9, 5)], [(3, 9), (4, 17), (12, 15), (11, 0), (10, 1), (8, 5), (13, 10), (14, 11)], [(0, 13), (1, 16)], [(0, 4), (1, 12), (6, 8), (9, 14), (15, 16), (17, 13)], [(0, 5), (3, 16), (7, 12), (17, 2), (11, 8)], [(0, 10), (7, 14), (10, 16), (11, 13), (6, 2), (9, 4), (15, 8), (17, 12)], [(1, 9), (2, 12), (5, 10), (6, 17), (8, 13), (12, 14), (10, 3), (17, 7), (15, 11)], [(2, 3), (5, 7)], [(16, 17), (12, 0), (8, 1), (13, 9)], [(0, 17), (1, 15), (3, 14), (4, 13), (9, 11), (10, 12), (12, 16), (5, 2), (7, 3), (11, 4), (6, 5), (17, 10)], [(3, 15), (4, 5), (7, 1), (13, 2), (11, 6)], [(5, 15), (8, 12), (10, 11), (13, 14), (15, 17), (1, 0), (6, 1), (4, 3), (12, 4), (11, 7), (17, 9), (16, 13)], [(0, 15), (1, 5), (3, 13), (4, 16), (9, 10), (11, 12), (15, 2), (7, 4), (10, 8)], [(0, 6), (3, 12), (4, 8), (7, 10), (9, 15), (14, 16), (10, 2), (17, 5)], [(8, 17), (2, 1), (13, 7), (12, 9), (16, 11)], [(0, 2), (7, 16), (9, 8)], [(4, 6), (14, 15), (3, 1), (13, 5)], [(0, 14), (1, 13), (6, 16)], [(2, 14), (6, 7), (5, 3)], [(2, 9), (8, 7)], [(2, 4), (5, 11), (6, 9), (8, 14), (15, 7)], [(1, 14), (6, 13)], [(0, 8), (9, 16)], [(13, 15), (14, 17), (3, 0), (4, 1), (16, 5), (12, 6)], [(3, 17), (4, 15), (7, 0), (11, 1), (16, 2), (12, 5), (10, 6), (14, 10)], [(3, 6), (14, 5)], [(0, 9), (1, 17), (2, 8), (4, 14), (6, 15), (8, 16), (12, 13), (11, 3), (10, 4), (9, 7), (15, 10), (17, 11)], [(3, 8), (11, 2), (9, 5)], [(3, 9), (4, 17), (12, 15), (11, 0), (10, 1), (8, 5), (13, 10), (14, 11)], [(0, 13), (1, 16)], [(0, 4), (1, 12), (6, 8), (9, 14), (15, 16), (17, 13)], [(0, 5), (3, 16), (7, 12), (17, 2), (11, 8)], [(0, 10), (7, 14), (10, 16), (11, 13), (6, 2), (9, 4), (15, 8), (17, 12)], [(1, 9), (2, 12), (5, 10), (6, 17), (8, 13), (12, 14), (10, 3), (17, 7), (15, 11)], [(2, 3), (5, 7)], [(16, 17), (12, 0), (8, 1), (13, 9)], [(0, 17), (1, 15), (3, 14), (4, 13), (9, 11), (10, 12), (12, 16), (5, 2), (7, 3), (11, 4), (6, 5), (17, 10)], [(3, 15), (4, 5), (7, 1), (13, 2), (11, 6)], [(5, 15), (8, 12), (10, 11), (13, 14), (15, 17), (1, 0), (6, 1), (4, 3), (12, 4), (11, 7), (17, 9), (16, 13)], [(0, 15), (1, 5), (3, 13), (4, 16), (9, 10), (11, 12), (15, 2), (7, 4), (10, 8)], [(0, 6), (3, 12), (4, 8), (7, 10), (9, 15), (14, 16), (10, 2), (17, 5)], [(8, 17), (2, 1), (13, 7), (12, 9), (16, 11)], [(0, 2), (7, 16), (9, 8)], [(4, 6), (14, 15), (3, 1), (13, 5)], [(0, 14), (1, 13), (6, 16)], [(2, 14), (6, 7), (5, 3)], [(2, 9), (8, 7)], [(2, 4), (5, 11), (6, 9), (8, 14), (15, 7)], [(1, 14), (6, 13)], [(0, 8), (9, 16)], [(13, 15), (14, 17), (3, 0), (4, 1), (16, 5), (12, 6)], [(3, 17), (4, 15), (7, 0), (11, 1), (16, 2), (12, 5), (10, 6), (14, 10)], [(3, 6), (14, 5)], [(0, 9), (1, 17), (2, 8), (4, 14), (6, 15), (8, 16), (12, 13), (11, 3), (10, 4), (9, 7), (15, 10), (17, 11)], [(3, 8), (11, 2), (9, 5)], [(3, 9), (4, 17), (12, 15), (11, 0), (10, 1), (8, 5), (13, 10), (14, 11)], [(0, 13), (1, 16)], [(0, 4), (1, 12), (6, 8), (9, 14), (15, 16), (17, 13)], [(0, 5), (3, 16), (7, 12), (17, 2), (11, 8)], [(0, 10), (7, 14), (10, 16), (11, 13), (6, 2), (9, 4), (15, 8), (17, 12)], [(1, 9), (2, 12), (5, 10), (6, 17), (8, 13), (12, 14), (10, 3), (17, 7), (15, 11)], [(2, 3), (5, 7)], [(16, 17), (12, 0), (8, 1), (13, 9)], [(0, 17), (1, 15), (3, 14), (4, 13), (9, 11), (10, 12), (12, 16), (5, 2), (7, 3), (11, 4), (6, 5), (17, 10)], [(3, 15), (4, 5), (7, 1), (13, 2), (11, 6)], [(5, 15), (8, 12), (10, 11), (13, 14), (15, 17), (1, 0), (6, 1), (4, 3), (12, 4), (11, 7), (17, 9), (16, 13)], [(0, 15), (1, 5), (3, 13), (4, 16), (9, 10), (11, 12), (15, 2), (7, 4), (10, 8)], [(0, 6), (3, 12), (4, 8), (7, 10), (9, 15), (14, 16), (10, 2), (17, 5)], [(8, 17), (2, 1), (13, 7), (12, 9), (16, 11)], [(0, 2), (7, 16), (9, 8)], [(4, 6), (14, 15), (3, 1), (13, 5)], [(0, 14), (1, 13), (6, 16)], [(2, 14), (6, 7), (5, 3)], [(2, 9), (8, 7)], [(2, 4), (5, 11), (6, 9), (8, 14), (15, 7)], [(1, 14), (6, 13)]]
freqs = np.linspace(.1,.2,16)
times = np.arange(3)
ants = np.arange(len(antpos))

info = Oi.RedundantInfo()
info.init_from_reds(reds, antpos)

In [11]:
import matplotlib.pyplot as plt
%matplotlib notebook 

In [12]:
def removedegen2(info, gains, vis, gainstart):
    '''Run removedegen.'''
    # divide out by gainstart (e.g. firstcal gains).    
    g,v = deepcopy(gains),deepcopy(vis)
    for ant in gains.keys():
        g[ant] /= gainstart[ant]
    
    # Calculate matrices used for projecting out degeneracies from antenna locations
    Rgains =  np.array([np.append(ai,1) for ai in info.antloc]) 
    Mgains = np.linalg.pinv(Rgains.T.dot(Rgains)).dot(Rgains.T) 
    Rvis = np.hstack((-info.ubl, np.zeros((len(info.ubl),1))))
    reds = info.get_reds()
    ntimes, nfreqs = gains.values()[0].shape
    
    for t in range(ntimes):
        for f in range(nfreqs):
            gainSols = np.array([g[ai][t,f] for ai in info.subsetant])
            visSols = np.array([vis[rg[0]][t,f] for rg in reds])
            
            #Fix amplitudes
            newGainSols = gainSols * np.exp(-1.0j * np.mean(np.angle(gainSols)))
            newGainSols = newGainSols / np.mean(np.abs(newGainSols))
            newVisSols = visSols * np.mean(np.abs(gainSols))**2 

            #Fix phases
            degenRemoved = Mgains.dot(np.angle(newGainSols))
            newGainSols = newGainSols * np.exp(-1.0j * Rgains.dot(degenRemoved))
            newVisSols = newVisSols * np.exp(-1.0j * Rvis.dot(degenRemoved))

            for i,ant in enumerate(info.subsetant): g[ant][t,f] = newGainSols[i]
            for i,rg in enumerate(reds): v[rg[0]][t,f] = newVisSols[i]    

    # multipy back in gainstart.
    for ai in g.keys():
        g[ai] *= gainstart[ai]

    return {}, g, v

In [18]:
# simulate unique "true" visibilities
np.random.seed(21)
vis_true = {}
i = 0
for rg in reds:
    vis_true[rg[0]] = np.array(1.0*np.random.randn(len(times),len(freqs)) 
                               + 1.0j*np.random.randn(len(times),len(freqs)), dtype=np.complex64)

fcgains = {}
for i in ants:
    fcspectrum = np.exp(2.0j * np.pi * 5.0 * np.random.randn() * freqs)
    fcgains[i] = np.array([fcspectrum for t in times], dtype=np.complex64)


gain_true = {}
for i in ants:
    gain_true[i] = np.array(1. + (.1*np.random.randn(len(times),len(freqs)) 
                            + .1j*np.random.randn(len(times),len(freqs))), dtype=np.complex64) 


#TODO: remove degen, apply firstcal gains, plot, fix the rest of the code
    
g0 = {i: np.ones_like(gain_true[i]) for i in ants}
_, gain_true, _ = removedegen2(info, gain_true, vis_true, g0)
for i in ants: gain_true[i] *= fcgains[i]
    

# plt.figure()
# plt.plot(np.array([np.angle(gain_true[i][0,:]) for i in ants]).T)



bl2ublkey = {bl: rg[0] for rg in reds for bl in rg}
data = {}
for rg in reds:
    for (i,j) in rg:
        data[(i,j)] = np.array(np.conj(gain_true[i]) * gain_true[j] * vis_true[rg[0]], dtype=np.complex64)

In [19]:
def chisq(data, g, v, reds):
    return np.mean(np.array([np.abs(data[(i,j)] - np.conj(g[i])*g[j]*v[rg[0]])**2 for rg in reds for (i,j) in rg]),axis=0)

In [23]:
def printDegens(info, gains, vis, fcgains):
    Rgains =  np.array([np.append(ai,1) for ai in info.antloc]) 
    Mgains = np.linalg.pinv(Rgains.T.dot(Rgains)).dot(Rgains.T) 
    ntimes, nfreqs = gains.values()[0].shape
    
    for t in range(ntimes):
        for f in range(nfreqs):
            gainSols = np.array([gains[ai][t,f]/fcgains[ai][t,f] for ai in info.subsetant])
            visSols = np.array([vis[rg[0]][t,f] for rg in reds])
            print np.mean(np.abs(gainSols)) - 1.0
            #print np.mean(np.angle(gainSols))
            #print Mgains.dot(np.angle(gainSols))


In [26]:


m1r,g1r,v1r = Oc.redcal(data, info, uselogcal=True)
m2r,g2r,v2r = Oc.redcal(data, info, gains=g1r, vis=v1r, uselincal=True)
_,g3r,v3r = Oc.redcal(data, info, gains=g2r, vis=v2r, removedegen=True)
#print m2r['chisq']
#print m2r['iter']
#print 'chisq:', chisq(data,g3r,v3r,reds)
#print v2r.keys()


# print v2r.keys()
# print vis_true.keys()
print '---------------------------------------------------'


g0 = {i: np.ones_like(gain_true[i]) for i in ants}
m1l, g1l, v1l = Oc.logcal(data, info, gainstart=fcgains)
m2l, g2l, v2l = Oc.lincal(data, info, gainstart=g1l, visstart=v1l,maxiter=400)
_, g3l, v3l = Oc.removedegen(info, g2l, v2l, fcgains)
_, g3l2, v3l2 = removedegen2(info, g2l, v2l, fcgains)
#print m2l['chisq']
print m2l['iter']
#print m['iter']

#for i in ants: g3l[i] *= fcgains[i]
#for i in ants: g3l2[i] *= fcgains[i]
print 'chisq:',chisq(data,g3l,v3l,reds)
print 'chisq:',chisq(data,g3l2,v3l2,reds)
print '---------------------------------------------------'


#printDegens(info, g3l2, v3l2, fcgains)
print '---------------------------------------------------'
printDegens(info, g3l, v3l, fcgains)
print '---------------------------------------------------'


---------------------------------------------------
[[ 6.  0.  2.  3.  0.  0.  0.  6.  0.  0.  0.  0.  2.  0.  0.  0.]
 [ 0.  0.  0.  0.  3.  0.  3.  3.  0.  0.  4.  2.  0.  0.  5.  0.]
 [ 0.  0.  7.  2.  0.  5.  0.  0.  0.  4.  0.  0.  0.  2.  0.  0.]]
chisq: [[  9.70300703e-14   2.02919712e-13   8.07629923e-14   1.24771761e-13
    8.15669757e-14   6.85970988e-14   1.16780229e-13   1.59862697e-13
    8.33182603e-14   5.92997195e-14   7.89005905e-14   1.42317310e-13
    9.78536710e-14   6.52284962e-14   1.06852258e-13   1.03153780e-13]
 [  9.92858546e-14   8.23600221e-14   1.29655631e-13   9.72197583e-14
    1.82131098e-13   7.84051508e-14   1.00329094e-13   7.95272187e-14
    9.36599905e-14   1.24611530e-13   7.39133757e-14   1.44963875e-13
    9.34178678e-14   8.53321117e-14   1.20743883e-13   1.42465209e-13]
 [  1.07257539e-13   8.18229761e-14   1.35588209e-13   1.58722848e-13
    1.32513358e-13   8.08967693e-14   1.30583505e-13   1.36418790e-13
    8.98712596e-14   8.87749143e-14  

In [25]:

print np.linalg.norm([g3l2[ant] - gain_true[ant] for ant in info.subsetant])
print np.linalg.norm([g3l[ant] - gain_true[ant] for ant in info.subsetant])
print np.linalg.norm([v3l2[bl] - vis_true[bl] for bl in vis_true.keys()])
print np.linalg.norm([v3l[bl] - vis_true[bl] for bl in vis_true.keys()])
print '---------------------------------------------------'
print np.max(np.abs([g3l2[ant] - gain_true[ant] for ant in info.subsetant]))
print np.max(np.abs([g3l[ant] - gain_true[ant] for ant in info.subsetant]))
print np.max(np.abs([v3l2[bl] - vis_true[bl] for bl in vis_true.keys()]))
print np.max(np.abs([v3l[bl] - vis_true[bl] for bl in vis_true.keys()]))



4.32286e-06
4.86732e-06
1.22144e-05
1.49339e-05
---------------------------------------------------
5.05762e-07
5.96791e-07
1.86592e-06
1.88486e-06
